### ISSUE TITLE
spellingci.inakalabs.com requires a username and password

### ISSUE THREAD

**Issue by srenatus** [inaka/spellingci#45]
Hi there.

Trying to access http://spellingci.inakalabs.com/ (or https://spellingci.inakalabs.com/), I'm facing a prompt asking me for username and password. Am I missing something? Are the README instructions not up to date?

Hope its ok to use this issue for my inquiry... 

Thanks! 😃 
Stephan

**Comment by ferigis** [comment]
Hi @srenatus, you were right. It should be working now. Thanks!

**Comment by srenatus** [comment]
🎉 Thanks! :+1:
